language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
# command to install dependencies
install:
  - "pip install ."
  - "pip install unittest2"
  - "if [[ $TRAVIS_PYTHON_VERSION != '2.5' ]]; then pip install coveralls; fi"
# command to run tests
script: python test_collections.py
after_success:
  "if [[ $TRAVIS_PYTHON_VERSION != '2.5' ]]; then coveralls; fi"
