language: python
python:
  - "2.6"
  - "2.7"
install:
  - "pip install ."
  - "pip install unittest2"
  - "pip install coverage"
  - "pip install coveralls"
script: >
          coverage run --append --branch --source=backport_collections test_collections.py &&
          coverage run --append --branch --source=backport_collections test_deque.py &&
          coverage run --append --branch --include=backport_collections.py backport_collections.py &&
          python setup.py sdist && pip install --upgrade dist/backport_collections-*.tar.gz
after_success:
  - "coverage report -m"
  - "coveralls"
