language: python
python:
  - "2.6"
  - "2.7"
install:
  - "pip install ."
  - "pip install unittest2"
  - "pip install coverage"
script: "coverage run --source=backport_collections test_collections.py && coverage run --source=backport_collections backport_collections.py"
after_success:
  coveralls
